name: Fetch and Push Elementals Metadata and Owners

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install axios
        run: npm install axios

      - name: Install ethers
        run: npm install ethers

      - name: Fetch metadata and save as JSON
        run: |
          node .github/scripts/fetch-elementals-metadata.mjs

      - name: Add owner info to metadata
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        run: node .github/scripts/add-owners-to-elementals.mjs

      - name: Add Twitter profiles to metadata
        run: node .github/scripts/add-twitter-profiles.mjs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: fetch and store elementals metadata with owner info and Twitter profiles"
          branch: update/elementals-metadata-${{ github.run_id }}
          title: "chore: fetch and store elementals metadata with owner info and Twitter profiles"
          body: "Automated update of elementals metadata, owner info, and Twitter profiles."
          base: ${{ github.ref_name }}
          delete-branch: true

      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge_method: squash
